NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/c2d_r50_ucf101_rgb_raw_dense_1x2x32'
TRAIN:
  MAX_ITER: 30000
  LOG_STEP: 10
  SAVE_STEP: 1000
  EVAL_STEP: 1000
  RESUME: False
  USE_TENSORBOARD: True
DATASETS:
  MODALITY: 'RGB'
  TYPE: 'RawFrame'
  SAMPLE_STRATEGY: 'DenseSample'
  CLIP_LEN: 1
  FRAME_INTERVAL: 2
  NUM_CLIPS: 32
  NUM_SAMPLE_POSITIONS: 1
  TRAIN:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
  TEST:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
TRANSFORM:
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  TRAIN:
    SCALE_JITTER: (256, 320)
    RANDOM_HORIZONTAL_FLIP: True
    COLOR_JITTER: (0.1, 0.1, 0.1, 0.1)
    RANDOM_ROTATION: 10
    RANDOM_CROP: True
    CENTER_CROP: False
    TRAIN_CROP_SIZE: 224
    RANDOM_ERASING: True
  TEST:
    SHORTER_SIDE: 256
    CENTER_CROP: True
    THREE_CROP: False
    TEST_CROP_SIZE: 256
DATALOADER:
  TRAIN_BATCH_SIZE: 12
  TEST_BATCH_SIZE: 12
  NUM_WORKERS: 8
MODEL:
  NAME: 'NL'
  PRETRAINED: ''
  SYNC_BN: True
  INPUT_SIZE: (224, 224, 3)
  BACKBONE:
    NAME: 'resnet3d_50'
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: True
    ZERO_INIT_RESIDUAL: True
    TYPE: 'C2D'
    IN_CHANNELS: 3
    SPATIAL_STRIDES: (1, 2, 2, 2)
    TEMPORAL_STRIDES: (1, 1, 1, 1)
    DILATIONS: (1, 1, 1, 1)
    BASE_CHANNEL: 64
    CONV1_KERNEL: (1, 7, 7)
    CONV1_STRIDE_T: 2
    POOL1_STRIDE_T: 2
    WITH_POOL2: True
    INFLATES: (0, 0, 0, 0)
    INFLATE_STYLE: '3x1x1'
    NON_LOCAL: (0, 0, 0, 0)
  HEAD:
    NAME: 'NLHead'
    FEATURE_DIMS: 2048
    DROPOUT: 0.5
    NUM_CLASSES: 101
  RECOGNIZER:
    NAME: 'NLRecognizer'
  CONSENSU:
    NAME: 'AvgConsensus'
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-3
  WEIGHT_DECAY: 1e-4
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'cosine_annearling_lr'
  IS_WARMUP: True
  COSINE_ANNEALING_LR:
    MINIMAL_LR: 3e-4
  WARMUP:
    ITERATION: 400
    MULTIPLIER: 1.0