DATASETS:
  MODALITY: 'RGB'
  SAMPLE_STRATEGY: 'DenseSample'
  CLIP_LEN: 1
  FRAME_INTERVAL: 2
  NUM_CLIPS: 32
  TRAIN:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
  TEST:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
TRANSFORM:
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  JITTER_SCALES: (256, 320)
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  RANDOM_ROTATION: 10
  COLOR_JITTER: (0.1, 0.1, 0.1, 0.1)
DATALOADER:
  TRAIN_BATCH_SIZE: 12
  TEST_BATCH_SIZE: 12
  NUM_WORKERS: 8
MODEL:
  NAME: 'NL'
  PRETRAINED: ""
  SYNC_BN: True
  INPUT_SIZE: (224, 224, 3)
  BACKBONE:
    NAME: 'resnet3d_50'
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: True
    ZERO_INIT_RESIDUAL: True
    TYPE: 'I3D_3x3x3'
    IN_CHANNELS: 3
    SPATIAL_STRIDES: (1, 2, 2, 2)
    TEMPORAL_STRIDES: (1, 1, 1, 1)
    DILATIONS: (1, 1, 1, 1)
    BASE_CHANNEL: 64
    CONV1_KERNEL: (5, 7, 7)
    CONV1_STRIDE_T: 2
    POOL1_STRIDE_T: 2
    WITH_POOL2: True
    INFLATES: ((1, 1, 1), (1, 0, 1, 0), (1, 0, 1, 0, 1, 0), (0, 1, 0))
    INFLATE_STYLE: '3x3x3'
    NON_LOCAL: (0, 0, 0, 0)
  HEAD:
    NAME: 'NLHead'
    FEATURE_DIMS: 2048
    DROPOUT: 0.0
    NUM_CLASSES: 101
  RECOGNIZER:
    NAME: 'NLRecognizer'
  CRITERION:
    NAME: 'crossentropy'
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-2
  WEIGHT_DECAY: 3e-4
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'cosine_annearling_lr'
  IS_WARMUP: True
  COSINE_ANNEALING_LR:
    MINIMAL_LR: 3e-4
  WARMUP:
    ITERATION: 1000
    MULTIPLIER: 1.0
TRAIN:
  MAX_ITER: 50000
OUTPUT:
  DIR: 'outputs/i3d-3x3_r3d50_ucf101_rgb_224x32_dense'