NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/x3d-s_r3d_ucf101_rgb_raw_dense_1x6x13'
TRAIN:
  MAX_ITER: 30000
  LOG_STEP: 10
  SAVE_STEP: 1000
  EVAL_STEP: 1000
  RESUME: False
  USE_TENSORBOARD: True
DATASETS:
  MODALITY: 'RGB'
  TYPE: 'RawFrame'
  SAMPLE_STRATEGY: 'DenseSample'
  CLIP_LEN: 1
  FRAME_INTERVAL: 6
  NUM_CLIPS: 13
  NUM_SAMPLE_POSITIONS: 1
  TRAIN:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
  TEST:
    NAME: 'UCF101'
    DATA_DIR: 'data/ucf101/rawframes'
    ANNOTATION_DIR: 'data/ucf101'
    SPLIT: 1
TRANSFORM:
  MEAN: (0.485, 0.456, 0.406)
  STD: (0.229, 0.224, 0.225)
  TRAIN:
    SCALE_JITTER: (182, 228)
    RANDOM_HORIZONTAL_FLIP: True
    COLOR_JITTER: (0.1, 0.1, 0.1, 0.1)
    RANDOM_ROTATION: 10
    RANDOM_CROP: True
    CENTER_CROP: False
    TRAIN_CROP_SIZE: 160
    RANDOM_ERASING: True
  TEST:
    SHORTER_SIDE: 182
    CENTER_CROP: True
    THREE_CROP: False
    TEST_CROP_SIZE: 182
DATALOADER:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 32
  NUM_WORKERS: 8
MODEL:
  NAME: 'X3D_S'
  PRETRAINED: ''
  SYNC_BN: True
  CONV_LAYER: 'Conv3d'
  POOL_LAYER: 'MaxPool3d'
  NORM_LAYER: 'BatchNorm3d'
  ACT_LAYER: 'ReLU'
  BACKBONE:
    NAME: 'X3D'
    IN_CHANNELS: 3
    PARTIAL_BN: False
    TORCHVISION_PRETRAINED: False
    ZERO_INIT_RESIDUAL: True
    BASE_CHANNEL: 24
    CONV1_LAYER: 'ChannelWiseConv3d'
    CONV1_KERNEL: (3, 3, 3)
    CONV1_STRIDE: (1, 2, 2)
    CONV1_PADDING: (1, 1, 1)
    WITH_POOL1: False
    WITH_POOL2: False
    STAGE_BLOCKS: (3, 5, 11, 7)
    RES_PLANES: (54, 108, 216, 432)
    EXPANSION: 0.445
    SPATIAL_STRIDES: (2, 2, 2, 2)
    INFLATES: (1,1,1,1)
    INFLATE_STYLE: '3x3x3'
  HEAD:
    NAME: 'X3DHead'
    FEATURE_DIMS: 192
    DROPOUT: 0.5
    NUM_CLASSES: 101
    CONV5_KERNEL: (1, 1, 1)
    CONV5_CHANNELS: 432
    POOL5_KERNEL: (13, 5, 5)
  RECOGNIZER:
    NAME: 'I3DRecognizer'
  CONSENSU:
    NAME: 'AvgConsensus'
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 1e-2
  WEIGHT_DECAY: 3e-5
  SGD:
    MOMENTUM: 0.9
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 15000, 25000 ]
  WARMUP:
    ITERATION: 400
    MULTIPLIER: 1.0